### ISSUE TITLE
Odd Pointer Areas

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/equality-explorer-basics#4]
In iOS 11 iPad Air 2 there are pointer areas in the home screen icon for the Lab screen as well as the Lab screen's navigation bar icon.  The pointer areas don't seem to do anything.  Is this intended?
For phetsims/QA/issues/145
Screenshot:
![pointer](https://user-images.githubusercontent.com/41024075/42717239-df4cb384-86bc-11e8-8af8-21be66e2ace9.jpg)

**Comment by pixelzoom** [comment]
This occurs on all platforms. The icon for the Lab screen is programmatically created (not an image file) using `NumberPicker`, which has default pointer areas.  The screen icon is set `pickable: false`, so the picker is not interactive.  But you'll see the pointer areas when running with `?showPointerAreas`.   They can safely be ignored, and it's not necessary to do anything about this.   But thanks for reporting.

Closing as "won't fix".
