### ISSUE TITLE
create auxiliary screenshots

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/equality-explorer-basics#5]
From #1

**Comment by phet-steele** [comment]
@KatieWoe please take these screenshots and follow the naming scheme from other sims:
![image](https://user-images.githubusercontent.com/5863899/48167320-995a1180-e2a8-11e8-9bcf-315292427129.png)

![image](https://user-images.githubusercontent.com/5863899/48167181-251f6e00-e2a8-11e8-9af2-b44fd45face6.png)

**Comment by amanda-phet** [comment]
For the first one should the coins be a little less organized?

Otherwise, the variety here looks nice .

**Comment by phet-steele** [comment]
> For the first one should the coins be a little less organized?

Up to @amanda-phet. Not a whole lot of un-organization you can really do in that one anyway.

**Comment by KatieWoe** [comment]
Final review for these two. @amanda-phet 
![equality-explorer-basics-screenshot-alt1](https://user-images.githubusercontent.com/41024075/48212573-2056ca80-e339-11e8-9c20-a5135c582a73.png)
![equality-explorer-basics-screenshot-alt2](https://user-images.githubusercontent.com/41024075/48212574-20ef6100-e339-11e8-8d8b-32e323adef04.png)

**Comment by amanda-phet** [comment]
For the Basics screen, just lay out the coins horizontally. 
![image](https://user-images.githubusercontent.com/7852916/48214746-db816280-e33d-11e8-9eee-ccfa4b270333.png)


Thanks!

**Comment by KatieWoe** [comment]
@amanda-phet 
![equality-explorer-basics-screenshot-alt1](https://user-images.githubusercontent.com/41024075/48215356-4f703a80-e33f-11e8-99f8-468ad166d860.png)

**Comment by amanda-phet** [comment]
Looks great! Thanks!

**Comment by KatieWoe** [comment]
Done
